# Generated by Django 4.1.5 on 2023-01-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('net_weight', models.CharField(max_length=50)),
                ('flavour', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('net_weight', models.CharField(max_length=50)),
                ('flavour', models.CharField(max_length=50)),
            ],
        ),
    ]
